[project]
name = "pydataromacapitale-website"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ics>=0.7.2",
    "markdown>=3.8",
    "pelican>=4.11.0",
    "requests>=2.32.3",
]
